/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.cine.ui;

import poo.cine.controller.GestorPersonaje;

/**
 *
 * @author Alumno
 */
public class PantallaGestorPersonajes extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer PantallaAdministracionPersonajes
     */
    public PantallaGestorPersonajes() {
        initComponents();
    }

    public PantallaGestorPersonajes(GestorPersonaje aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("poo-01-cinePU").createEntityManager();
        txtNombreEnPelicula = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        SelActor = new javax.swing.JComboBox<>();
        label2 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        btnCargarNuevoActor = new java.awt.Button();
        btnGuardar = new java.awt.Button();
        btnSalir = new java.awt.Button();
        label3 = new java.awt.Label();
        SelRol = new javax.swing.JComboBox<>();

        setVerifyInputWhenFocusTarget(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreEnPelicula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreEnPeliculaFocusLost(evt);
            }
        });
        txtNombreEnPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEnPeliculaActionPerformed(evt);
            }
        });
        txtNombreEnPelicula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreEnPeliculaKeyPressed(evt);
            }
        });
        add(txtNombreEnPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, -1));
        txtNombreEnPelicula.getAccessibleContext().setAccessibleParent(txtNombreEnPelicula);

        label1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        label1.setText("Nombre en Película");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        SelActor.setModel(new javax.swing.DefaultComboBoxModel(actor.toArray()));
        SelActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelActorActionPerformed(evt);
            }
        });
        add(SelActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 180, -1));

        label2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        label2.setText("Actor");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        btnCargarNuevoActor.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnCargarNuevoActor.setLabel("Cargar Nuevo Actor");
        btnCargarNuevoActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarNuevoActorActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargarNuevoActor);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnGuardar.setLabel("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar);

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnSalir.setLabel("Salir");
        jPanel1.add(btnSalir);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 360, 40));

        label3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        label3.setText("Rol");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        SelRol.setModel(new javax.swing.DefaultComboBoxModel(rol.toArray()));
        add(SelRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void SelActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelActorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelActorActionPerformed

    private void txtNombreEnPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEnPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEnPeliculaActionPerformed

    private void btnCargarNuevoActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarNuevoActorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarNuevoActorActionPerformed

    private void txtNombreEnPeliculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreEnPeliculaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEnPeliculaFocusLost

    private void txtNombreEnPeliculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEnPeliculaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEnPeliculaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SelActor;
    private javax.swing.JComboBox<String> SelRol;
    private java.awt.Button btnCargarNuevoActor;
    private java.awt.Button btnGuardar;
    private java.awt.Button btnSalir;
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextField txtNombreEnPelicula;
    // End of variables declaration//GEN-END:variables
}
